### PR TITLE
chore(dev): improve local dev experience

### PR DESCRIPTION
**Pull request by jschmid1**

### CODE REVIEW

**Comment by jschmid1** [comment]
```
#15 34.18 ERROR: Could not find a version that satisfies the requirement pygtrie==2.4.2 (from versions: 0.9.1, 0.9.2, 0.9.3, 1.0, 1.1, 1.2, 2.0, 2.1, 2.2, 2.3, 2.3.2, 2.3.3, 2.4.0, 2.4.1, 2.4.2)
#15 34.18 ERROR: No matching distribution found for pygtrie==2.4.2
#15 ERROR: executor failed running [/bin/sh -c /opt/pulp/bin/pip install -U -r /opt/pulp/pulp-requirements.txt]: exit code: 1

```

seems terribly unrelated

**Comment by dannysauer** [comment]
That line above showing it discarding the file - https://github.com/Kong/docker-pulp/runs/4105533950?check_suite_focus=true#step:6:1457 - is suspicious. But it also means the image won't build and thus won't be published. I kicked it again, and it failed again. I wonder if that package is broken upstream.

I haven't tried building locally. Maybe check the changelog to ensure it's not a security risk and bump it back down a version? 🤷‍♂️

**Comment by jschmid1** [comment]
I cannot find any direct hints when installing this package:

```
Installing collected packages: pygtrie
    Running setup.py install for pygtrie ... done
Successfully installed pygtrie-2.4.2
```

I'll let this sit for a day and hope that it magically resolves itself.

**Comment by jschmid1** [comment]
🪄

**Review by dannysauer — APPROVED** [review]
Hooray for magic!

**Pull request merged**
